"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones, configureBoneyard } from 'boneyard-js/react'

import _landing_hero from './landing-hero.bones.json'

configureBoneyard({"color":"rgba(0,0,0,0.08)","animate":"pulse"})

registerBones({
  "landing-hero": _landing_hero,
})
