"""Initial_Schema

Revision ID: c4f30408fbb8
Revises: 
Create Date: 2026-02-14 21:16:47.988852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c4f30408fbb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    if is_sqlite:
        geo_type = sa.JSON()
    else:
        geo_type = geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, from_text='ST_GeogFromText', name='geography')

    op.add_column('alerts', sa.Column('geom', geo_type, nullable=True))
    if not is_sqlite:
        op.create_index('idx_alerts_geom', 'alerts', ['geom'], unique=False, postgresql_using='gist')
    
    op.add_column('community_reports', sa.Column('geom', geo_type, nullable=True))
    if not is_sqlite:
        op.create_index('idx_community_reports_geom', 'community_reports', ['geom'], unique=False, postgresql_using='gist')

    op.add_column('status_checks', sa.Column('geom', geo_type, nullable=True))
    if not is_sqlite:
        op.create_index('idx_status_checks_geom', 'status_checks', ['geom'], unique=False, postgresql_using='gist')

    op.add_column('users', sa.Column('geom', geo_type, nullable=True))
    if not is_sqlite:
        op.create_index('idx_users_geom', 'users', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'

    if not is_sqlite:
        op.drop_index('idx_users_geom', table_name='users', postgresql_using='gist')
    op.drop_column('users', 'geom')

    if not is_sqlite:
        op.drop_index('idx_status_checks_geom', table_name='status_checks', postgresql_using='gist')
    op.drop_column('status_checks', 'geom')

    if not is_sqlite:
        op.drop_index('idx_community_reports_geom', table_name='community_reports', postgresql_using='gist')
    op.drop_column('community_reports', 'geom')

    if not is_sqlite:
        op.drop_index('idx_alerts_geom', table_name='alerts', postgresql_using='gist')
    op.drop_column('alerts', 'geom')
    # ### end Alembic commands ###
